### ISSUE TITLE
avoid attempts of logging `None` values to mlflow

### ISSUE THREAD

**Issue by pascal456** [fhdw-forschung/modelling-tools#117]
# problem

Cannot log `None` values to mlflow:

```
Traceback (most recent call last):
  File "/workspaces/bebefam-exploration/experiments/tpot_costs_myneo.py", line 149, in <module>
    main(targets=TARGETS, verbose=False, config=tpot_config)
  File "/workspaces/bebefam-exploration/experiments/tpot_costs_myneo.py", line 109, in main
    log_metrics_to_mlflow(y_true=y_test, y_pred=y_pred)
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/fhdw/modelling/tracking.py", line 25, in log_metrics_to_mlflow
    mlflow.log_metrics(metrics=metrics)
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/mlflow/tracking/fluent.py", line 650, in log_metrics
    MlflowClient().log_batch(run_id=run_id, metrics=metrics_arr, params=[], tags=[])
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/mlflow/tracking/client.py", line 918, in log_batch
    self._tracking_client.log_batch(run_id, metrics, params, tags)
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/client.py", line 320, in log_batch
    self.store.log_batch(run_id=run_id, metrics=metrics_batch, params=[], tags=[])
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/mlflow/store/tracking/rest_store.py", line 303, in log_batch
    metric_protos = [metric.to_proto() for metric in metrics]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/mlflow/store/tracking/rest_store.py", line 303, in <listcomp>
    metric_protos = [metric.to_proto() for metric in metrics]
                     ^^^^^^^^^^^^^^^^^
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/mlflow/entities/metric.py", line 39, in to_proto
    metric.value = self.value
    ^^^^^^^^^^^^
TypeError: must be real number, not NoneType
```

# proposal

- filter out the none values before the mlflow log function
or
- leave out the the `None` entry in the first place

In the end this is most probably about negative values, i.e. RMSLE cannot be calculated

**Comment by pascal456** [comment]
e.g. adding

```python
metrics = {key: value for key, value in metrics.items() if value is not None}
```

as a filter

or

change creation of
https://github.com/fhdw-forschung/modelling-tools/blob/6bc1c0fae3c03324c297b113f284f6bf2c674c94/fhdw/modelling/evaluation.py#L15-L41
