### ISSUE TITLE
plot function error when data not given

### ISSUE THREAD

**Issue by pascal456** [fhdw-forschung/modelling-tools#94]
```
Traceback (most recent call last):
  File "/workspaces/bebefam-exploration/experiments/tpot_test_skript.py", line 77, in <module>
    main()
  File "/workspaces/bebefam-exploration/experiments/tpot_test_skript.py", line 72, in main
    fig_identity = plot_actual_vs_pred(y_true=x_test, y_pred=y_pred, target=target)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/bebefam-exploration/bebefam/modelling/evaluation.py", line 120, in plot_actual_vs_pred
    figure = px.scatter(
             ^^^^^^^^^^^
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/plotly/express/_chart_types.py", line 66, in scatter
    return make_figure(args=locals(), constructor=go.Scatter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/plotly/express/_core.py", line 2076, in make_figure
    args = build_dataframe(args, constructor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/plotly/express/_core.py", line 1485, in build_dataframe
    df_output, wide_id_vars = process_args_into_dataframe(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/plotly/express/_core.py", line 1256, in process_args_into_dataframe
    df_output[str(col_name)] = to_unindexed_series(argument, str(col_name))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/plotly/express/_core.py", line 1073, in to_unindexed_series
    return pd.Series(x, name=name).reset_index(drop=True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/pandas/core/series.py", line 386, in __init__
    if is_empty_data(data) and dtype is None:
       ^^^^^^^^^^^^^^^^^^^
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/pandas/core/construction.py", line 877, in is_empty_data
    is_simple_empty = is_list_like_without_dtype and not data
                                                     ^^^^^^^^
  File "/workspaces/bebefam-exploration/.venv/lib/python3.11/site-packages/pandas/core/generic.py", line 1527, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by pascal456** [comment]
turned out to be a problem in the setup. gave `x_test` instead of `y_test`, therefore shape was wrong, leading to this error
